// apps/web/src/components/solid/dashboard/feeds-panel.tsx
import { actions } from "astro:actions";
import { createForm, Field as FormField, Form, reset } from "@formisch/solid";
import { PencilIcon, PlusIcon, Trash2Icon, XIcon } from "lucide-solid";
import { createSignal, For, Show } from "solid-js";
import * as v from "valibot";
import { cn, formatDate } from "../../../lib/utils";
import { Button } from "../ui/button";
import { Field, FieldError, FieldGroup, FieldLabel } from "../ui/field";
import { Input } from "../ui/input";
import { Spinner } from "../ui/spinner";
import { RichTextEditor } from "./rich-text-editor";

interface Feed {
	id: string;
	tag: string;
	content: string;
	draft: boolean;
	createdAt: string;
	updatedAt: string;
}

type FormMode = { type: "create" } | { type: "edit"; feed: Feed };

const FeedSchema = v.object({
	tag: v.pipe(v.string("Tag is required"), v.minLength(1, "Tag is required")),
	content: v.pipe(
		v.string(),
		v.check((content) => content.replace(/<[^>]*>/g, "").trim().length > 0, "Content is required")
	),
	draft: v.boolean(),
});

function FeedForm(props: {
	mode: FormMode;
	onClose: () => void;
	onSaved: () => void;
	onError: (message: string) => void;
}) {
	const form = createForm({
		schema: FeedSchema,
		initialInput: {
			tag: props.mode.type === "edit" ? props.mode.feed.tag : "",
			content: props.mode.type === "edit" ? props.mode.feed.content : "",
			draft: props.mode.type === "edit" ? props.mode.feed.draft : false,
		},
	});

	const onSubmit = async (output: v.InferOutput<typeof FeedSchema>) => {
		const fd = new FormData();
		fd.append("tag", output.tag);
		fd.append("content", output.content);
		fd.append("draft", String(output.draft));

		if (props.mode.type === "edit") {
			fd.append("id", props.mode.feed.id);
			const { error } = await actions.updateFeed(fd);

			if (error) {
				props.onError(error.message);
				return;
			}
		} else {
			const { error } = await actions.createFeed(fd);

			if (error) {
				props.onError(error.message);
				return;
			}
		}

		reset(form);
		props.onSaved();
	};

	return (
		<div class="border border-border p-6 space-y-4">
			<div class="flex items-center justify-between">
				<h3 class="font-serif text-2xl">
					{props.mode.type === "create" ? "New Feed Entry" : "Edit Feed Entry"}
				</h3>
				<button
					type="button"
					onClick={props.onClose}
					class="text-foreground/50 hover:text-foreground"
					aria-label="Close"
				>
					<XIcon class="size-4" />
				</button>
			</div>

			<Form of={form} onSubmit={onSubmit}>
				<FieldGroup>
					<div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
						<FormField of={form} path={["tag"]}>
							{(field) => {
								const isInvalid = () => field.isTouched && !field.isValid;

								return (
									<Field data-invalid={isInvalid()}>
										<FieldLabel for={field.props.name}>Tag</FieldLabel>
										<Input
											{...field.props}
											value={field.input}
											placeholder="e.g. meta, oss, feature"
											aria-invalid={isInvalid()}
										/>
										<Show when={isInvalid()}>
											<FieldError errors={field.errors} />
										</Show>
									</Field>
								);
							}}
						</FormField>
					</div>

					<FormField of={form} path={["content"]}>
						{(field) => (
							<Field data-invalid={!!field.errors}>
								<FieldLabel>Content</FieldLabel>
								<RichTextEditor
									defaultValue={field.input}
									onChange={(html) => field.onInput(html)}
								/>
								<Show when={field.errors}>
									<FieldError errors={field.errors} />
								</Show>
							</Field>
						)}
					</FormField>

					<FormField of={form} path={["draft"]}>
						{(field) => (
							<Field orientation="horizontal">
								<input
									id={field.props.name}
									type="checkbox"
									{...field.props}
									checked={field.input}
									class="size-4"
								/>
								<FieldLabel for={field.props.name}>Draft (hidden from public)</FieldLabel>
							</Field>
						)}
					</FormField>

					<div class="flex gap-2">
						<Button type="submit" disabled={form.isSubmitting}>
							<Show when={form.isSubmitting}>
								<Spinner />
							</Show>
							Save
						</Button>
						<Button type="button" variant="outline" onClick={props.onClose}>
							Cancel
						</Button>
					</div>
				</FieldGroup>
			</Form>
		</div>
	);
}

export function FeedsPanel(props: { feeds: Feed[] }) {
	const [feeds, setFeeds] = createSignal<Feed[]>(props.feeds);
	const [formMode, setFormMode] = createSignal<FormMode | null>(null);
	const [status, setStatus] = createSignal<{ type: "error" | "success"; text: string }>();
	const [deletingId, setDeletingId] = createSignal<string>();

	const refetch = async () => {
		const { data, error } = await actions.getAdminFeeds();
		if (!error) setFeeds(data);
	};

	const onDelete = async (id: string) => {
		if (!confirm("Delete this feed entry?")) return;

		setDeletingId(id);

		const fd = new FormData();
		fd.append("id", id);

		const { error } = await actions.deleteFeed(fd);

		if (error) {
			setStatus({ type: "error", text: "Failed to delete." });
			setDeletingId(undefined);
			return;
		}

		setStatus({ type: "success", text: "Feed entry deleted." });
		setDeletingId(undefined);
		await refetch();
	};

	return (
		<div class="space-y-6">
			<Show
				when={formMode()}
				fallback={
					<div class="flex justify-between items-center gap-4">
						<Show when={status()}>
							<p
								class={cn(
									"font-mono text-xs",
									status()?.type === "error" ? "text-destructive" : "text-foreground/50"
								)}
							>
								{status()?.text}
							</p>
						</Show>
						<div class="ml-auto">
							<Button onClick={() => setFormMode({ type: "create" })}>
								<PlusIcon class="size-4" />
								New Entry
							</Button>
						</div>
					</div>
				}
			>
				<FeedForm
					mode={formMode() as FormMode}
					onClose={() => setFormMode(null)}
					onSaved={() => {
						setStatus({
							type: "success",
							text: formMode()?.type === "edit" ? "Feed entry updated." : "Feed entry created.",
						});
						setFormMode(null);
						refetch();
					}}
					onError={(message) => setStatus({ type: "error", text: message })}
				/>
			</Show>

			<Show
				when={feeds().length === 0}
				fallback={
					<div class="space-y-3">
						<For each={feeds()}>
							{(feed) => (
								<div class="border border-border p-4 flex items-start justify-between gap-4">
									<div class="space-y-1 min-w-0">
										<div class="flex items-center gap-3 flex-wrap">
											<span class="font-mono text-xs text-foreground/50 uppercase tracking-widest">
												{formatDate(new Date(feed.createdAt))}
											</span>
											<span class="font-mono text-xs uppercase tracking-widest border border-border px-2 py-0.5 text-foreground/60">
												{feed.tag}
											</span>
											<Show when={feed.draft}>
												<span class="font-mono text-xs uppercase tracking-widest border border-yellow-600 text-yellow-600 px-2 py-0.5">
													Draft
												</span>
											</Show>
										</div>
										<div class="prose prose-sm dark:prose-invert" innerHTML={feed.content} />
									</div>
									<div class="flex gap-2 shrink-0">
										<button
											type="button"
											onClick={() => setFormMode({ type: "edit", feed })}
											class="text-foreground/40 hover:text-foreground duration-200"
											aria-label="Edit"
										>
											<PencilIcon class="size-4" />
										</button>
										<button
											type="button"
											onClick={() => onDelete(feed.id)}
											disabled={deletingId() === feed.id}
											class="text-foreground/40 hover:text-destructive duration-200"
											aria-label="Delete"
										>
											<Show
												when={deletingId() === feed.id}
												fallback={<Trash2Icon class="size-4" />}
											>
												<Spinner class="size-4" />
											</Show>
										</button>
									</div>
								</div>
							)}
						</For>
					</div>
				}
			>
				<div class="border border-dashed border-border py-16 flex flex-col items-center justify-center gap-4 text-center">
					<p class="font-serif text-2xl text-foreground/40">Nothing here yet.</p>
					<p class="text-sm text-foreground/40 max-w-xs">
						Feed entries you create will show up here. Hit "New Entry" to write your first one.
					</p>
					<Button variant="outline" onClick={() => setFormMode({ type: "create" })}>
						<PlusIcon class="size-4" />
						New Entry
					</Button>
				</div>
			</Show>
		</div>
	);
}

// src/routes/dashboard/_admin/admin/-feeds-panel.tsx
import { useForm } from "@tanstack/react-form";
import {
  useMutation,
  useQueryClient,
  useSuspenseQuery,
} from "@tanstack/react-query";
import { PencilIcon, PlusIcon, Trash2Icon, XIcon } from "lucide-react";
import { type SubmitEvent, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import {
  Field,
  FieldError,
  FieldGroup,
  FieldLabel,
} from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { RichTextEditor } from "@/components/ui/rich-text-editor";
import { Spinner } from "@/components/ui/spinner";
import {
  createFeedMutationOptions,
  deleteFeedMutationOptions,
  getAdminFeedsQueryOptions,
  updateFeedMutationOptions,
} from "@/fns/polymorphic/feeds";
import { formatDate } from "@/lib/utils";

type Feed = {
  id: string;
  tag: string;
  content: string;
  draft: boolean;
};

type FormMode = { type: "create" } | { type: "edit"; feed: Feed };

function FeedForm({ mode, onClose }: { mode: FormMode; onClose: () => void }) {
  const queryClient = useQueryClient();
  const createMutation = useMutation(createFeedMutationOptions);
  const updateMutation = useMutation(updateFeedMutationOptions);

  const initial = mode.type === "edit" ? mode.feed : null;

  const invalidate = () =>
    Promise.all([
      queryClient.invalidateQueries({
        queryKey: getAdminFeedsQueryOptions.queryKey,
      }),
      queryClient.invalidateQueries({ queryKey: ["public-feeds"] }),
    ]);

  const form = useForm({
    defaultValues: {
      tag: initial?.tag ?? "",
      content: initial?.content ?? "",
      draft: initial?.draft ?? false,
    },
    onSubmit: async ({ value }) => {
      const plainContent = value.content.replace(/<[^>]*>/g, "").trim();
      if (!plainContent) {
        form.setFieldMeta("content", (prev) => ({
          ...prev,
          errorMap: {
            onChange: "Content is required",
          },
        }));
        return;
      }

      try {
        if (mode.type === "create") {
          await createMutation.mutateAsync({ data: value });
          toast.success("Feed entry created.");
        } else {
          await updateMutation.mutateAsync({
            data: { id: mode.feed.id, ...value },
          });
          toast.success("Feed entry updated.");
        }
        await invalidate();
        onClose();
      } catch {
        toast.error("Something went wrong.");
      }
    },
  });

  const onSubmit = (e: SubmitEvent<HTMLFormElement>) => {
    e.preventDefault();
    form.handleSubmit(e.target);
  };

  return (
    <div className="border border-border p-6 space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="font-serif text-2xl">
          {mode.type === "create" ? "New Feed Entry" : "Edit Feed Entry"}
        </h3>
        <button
          type="button"
          onClick={onClose}
          className="text-foreground/50 hover:text-foreground"
        >
          <XIcon className="size-4" />
        </button>
      </div>

      <form onSubmit={onSubmit}>
        <FieldGroup>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <form.Field
              name="tag"
              validators={{
                onChange: ({ value }) =>
                  !value.trim() ? "Tag is required" : undefined,
              }}
            >
              {(field) => {
                const isInvalid =
                  field.state.meta.isTouched && !field.state.meta.isValid;

                return (
                  <Field data-invalid={isInvalid}>
                    <FieldLabel htmlFor={field.name}>Tag</FieldLabel>
                    <Input
                      id={field.name}
                      value={field.state.value}
                      onBlur={field.handleBlur}
                      onChange={(e) => field.handleChange(e.target.value)}
                      placeholder="e.g. meta, oss, feature"
                      aria-invalid={isInvalid}
                    />
                    {isInvalid && (
                      <FieldError
                        errors={field.state.meta.errors.map((e) => ({
                          message: String(e),
                        }))}
                      />
                    )}
                  </Field>
                );
              }}
            </form.Field>
          </div>

          <form.Field name="content">
            {(field) => {
              const errors = field.state.meta.errorMap?.onChange;
              return (
                <Field data-invalid={!!errors}>
                  <FieldLabel>Content</FieldLabel>
                  <RichTextEditor
                    defaultValue={field.state.value}
                    onChange={(html) => field.handleChange(html)}
                  />
                  {errors && (
                    <FieldError errors={[{ message: String(errors) }]} />
                  )}
                </Field>
              );
            }}
          </form.Field>

          <form.Field name="draft">
            {(field) => (
              <Field orientation="horizontal">
                <input
                  id={field.name}
                  type="checkbox"
                  checked={field.state.value}
                  onChange={(e) => field.handleChange(e.target.checked)}
                  className="size-4"
                />
                <FieldLabel htmlFor={field.name}>
                  Draft (hidden from public)
                </FieldLabel>
              </Field>
            )}
          </form.Field>

          <div className="flex gap-2">
            <form.Subscribe selector={(s) => s.isSubmitting}>
              {(isSubmitting) => (
                <Button type="submit" disabled={isSubmitting}>
                  {isSubmitting && <Spinner />}
                  Save
                </Button>
              )}
            </form.Subscribe>
            <Button type="button" variant="outline" onClick={onClose}>
              Cancel
            </Button>
          </div>
        </FieldGroup>
      </form>
    </div>
  );
}

export function FeedsPanel() {
  const queryClient = useQueryClient();
  const { data: feeds } = useSuspenseQuery(getAdminFeedsQueryOptions);
  const deleteMutation = useMutation(deleteFeedMutationOptions);

  const [formMode, setFormMode] = useState<FormMode | null>(null);

  const onDelete = async (id: string) => {
    if (!confirm("Delete this feed entry?")) return;
    try {
      await deleteMutation.mutateAsync({ data: { id } });
      await Promise.all([
        queryClient.invalidateQueries({
          queryKey: getAdminFeedsQueryOptions.queryKey,
        }),
        queryClient.invalidateQueries({ queryKey: ["public-feeds"] }),
      ]);
      toast.success("Feed entry deleted.");
    } catch {
      toast.error("Failed to delete.");
    }
  };

  return (
    <div className="space-y-6">
      {formMode ? (
        <FeedForm mode={formMode} onClose={() => setFormMode(null)} />
      ) : (
        <div className="flex justify-end">
          <Button onClick={() => setFormMode({ type: "create" })}>
            <PlusIcon className="size-4" />
            New Entry
          </Button>
        </div>
      )}

      {feeds.length === 0 ? (
        <div className="border border-dashed border-border py-16 flex flex-col items-center justify-center gap-4 text-center">
          <p className="font-serif text-2xl text-foreground/40">
            Nothing here yet.
          </p>
          <p className="text-sm text-foreground/40 max-w-xs">
            Feed entries you create will show up here. Hit "New Entry" to write
            your first one.
          </p>
          <Button
            variant="outline"
            onClick={() => setFormMode({ type: "create" })}
          >
            <PlusIcon className="size-4" />
            New Entry
          </Button>
        </div>
      ) : (
        <div className="space-y-3">
          {feeds.map((feed) => (
            <div
              key={feed.id}
              className="border border-border p-4 flex items-start justify-between gap-4"
            >
              <div className="space-y-1 min-w-0">
                <div className="flex items-center gap-3 flex-wrap">
                  <span className="font-mono text-xs text-foreground/50 uppercase tracking-widest">
                    {formatDate(feed.createdAt)}
                  </span>
                  <span className="font-mono text-xs uppercase tracking-widest border border-border px-2 py-0.5 text-foreground/60">
                    {feed.tag}
                  </span>
                  {feed.draft && (
                    <span className="font-mono text-xs uppercase tracking-widest border border-yellow-600 text-yellow-600 px-2 py-0.5">
                      Draft
                    </span>
                  )}
                </div>
                <p className="text-sm text-foreground/70 truncate">
                  {feed.content.replace(/<[^>]*>/g, "").slice(0, 120)}
                </p>
              </div>
              <div className="flex gap-2 shrink-0">
                <button
                  type="button"
                  onClick={() => setFormMode({ type: "edit", feed })}
                  className="text-foreground/40 hover:text-foreground duration-200"
                  aria-label="Edit"
                >
                  <PencilIcon className="size-4" />
                </button>
                <button
                  type="button"
                  onClick={() => onDelete(feed.id)}
                  disabled={deleteMutation.isPending}
                  className="text-foreground/40 hover:text-destructive duration-200"
                  aria-label="Delete"
                >
                  <Trash2Icon className="size-4" />
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
