// src/components/solid/Button.tsx
import { cn } from "@/lib/utils";
import { cva } from "@/utils/cva";
import type { VariantProps } from "cva";
import { type ComponentProps } from "solid-js";
import { Dynamic } from "solid-js/web";

const buttonVariants = cva({
	base: "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4 shrink-0 [&_svg]:shrink-0 outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive cursor-pointer",
	variants: {
		variant: {
			default: "bg-primary text-primary-foreground hover:bg-primary/90",
			destructive:
				"bg-destructive text-white hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60",
			outline:
				"border bg-background shadow-xs hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50",
			secondary: "bg-secondary text-secondary-foreground hover:bg-secondary/80",
			ghost: "hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50",
			link: "text-primary underline-offset-4 hover:underline",
		},
		size: {
			default: "h-9 px-4 py-2 has-[>svg]:px-3",
			sm: "h-8 rounded-md gap-1.5 px-3 has-[>svg]:px-2.5",
			lg: "h-10 rounded-md px-6 has-[>svg]:px-4",
			xl: "h-12 rounded-md px-8 has-[>svg]:px-6",
			icon: "size-9",
			"icon-sm": "size-8",
			"icon-lg": "size-10",
		},
	},
	defaultVariants: {
		variant: "default",
		size: "default",
	},
});

function Button({
	class: className,
	variant,
	size,
	children,
	asChild,
	...props
}: ComponentProps<"button"> &
	VariantProps<typeof buttonVariants> & {
		asChild?: boolean;
	}) {
	if (asChild) {
		return <Dynamic component={() => children} />;
	}

	return (
		<button
			data-slot="button"
			class={cn(buttonVariants({ variant, size, className }))}
			children={children}
			{...props}
		/>
	);
}

export { Button, buttonVariants };

// src/components/base/Button.tsx
import { Loader2 } from 'lucide-react'
import {
  type ButtonHTMLAttributes,
  forwardRef,
  type PropsWithChildren,
} from 'react'
import { cn } from '@/libs/utils'

export interface ButtonProps
  extends PropsWithChildren<ButtonHTMLAttributes<HTMLButtonElement>> {
  isLoading?: boolean
  inverted?: boolean
  asChild?: boolean
}

export const buttonClassName =
  'p-6 border border-stone-300 relative after:bg-white after:absolute after:inset-0 after:-translate-y-full after:duration-300 hover:after:translate-y-0 overflow-hidden bg-stone-700 outline-none text-white font-heading uppercase tracking-wider text-xl hover:text-stone-700 w-full cursor-pointer focus-visible:ring-stone-400 focus-visible:ring-[2px]'

export const buttonClassNameInverted =
  'bg-white after:bg-stone-700 text-stone-700 hover:text-white after:translate-y-full hover:after:translate-y-0'

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  (
    { className, children, isLoading, disabled, inverted, asChild, ...props },
    ref,
  ) => {
    return (
      <button
        className={cn(
          buttonClassName,
          {
            'opacity-80 pointer-events-none': isLoading,
            [buttonClassNameInverted]: inverted,
          },
          className,
        )}
        disabled={isLoading || disabled}
        {...props}
        ref={ref}
      >
        <div className="z-10 relative flex items-center gap-2 justify-center">
          {isLoading ? <Loader2 className="animate-spin size-7" /> : children}
        </div>
      </button>
    )
  },
)

export default Button
